name: Qt CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install required packages for Qt and C++
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y qtbase5-dev qtchooser qt5-qmake qttools5-dev-tools cmake g++

      # Step 3: Configure and compile the project
      - name: Configure and Build
        run: |
          cmake .
          make

      # Step 4: Execute the compiled Qt application
      - name: Run Application
        run: ./qt_ci_cd_demo

